[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "nginx -g 'daemon off;'"
restartPolicyType = "ALWAYS"
healthcheckPath = "/health/"
healthcheckTimeout = 300

[variables]
BACKEND_URL = "https://celebra-capital-production.up.railway.app/api/" 