name: Testes de Acessibilidade

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * 1' # Toda segunda-feira às 00:00

jobs:
  a11y-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Start development server
        run: |
          cd frontend
          npm run dev &
          sleep 10 # Aguardar o servidor iniciar

      - name: Run accessibility tests
        run: |
          cd frontend
          npm run test:a11y:ci
        env:
          BASE_URL: http://localhost:3000

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: a11y-report
          path: frontend/a11y-reports/
          retention-days: 7

      - name: Check for critical violations
        if: always()
        run: |
          cd frontend
          VIOLATIONS=$(grep -r '"impact":"critical"' a11y-reports/ | wc -l)
          if [ $VIOLATIONS -gt 0 ]; then
            echo "❌ Encontradas $VIOLATIONS violações críticas de acessibilidade"
            exit 1
          else
            echo "✅ Nenhuma violação crítica encontrada"
          fi
