name: Testes de Acessibilidade

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  # Permite executar o workflow manualmente a partir da aba Actions
  workflow_dispatch:

jobs:
  accessibility-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Instalar dependências
        run: |
          cd frontend
          npm ci

      - name: Executar testes de acessibilidade
        run: |
          cd frontend
          npm run test:a11y

      - name: Gerar relatório de acessibilidade
        run: |
          cd frontend
          npm run test:a11y:report

      - name: Armazenar relatórios de acessibilidade
        uses: actions/upload-artifact@v3
        with:
          name: accessibility-reports
          path: frontend/reports/accessibility
          if-no-files-found: warn

      - name: Publicar comentário com resumo no PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');

            try {
              // Ler o resumo do relatório
              const summaryFile = 'frontend/reports/accessibility/summary.md';
              
              let summaryContent = '';
              if (fs.existsSync(summaryFile)) {
                summaryContent = fs.readFileSync(summaryFile, 'utf8');
              } else {
                summaryContent = '### Resumo dos Testes de Acessibilidade\n\nNenhum resumo disponível. Verifique os artefatos para relatórios detalhados.';
              }
              
              // Adicionar comentário ao PR
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: summaryContent
              });
            } catch (error) {
              console.error('Erro ao publicar comentário:', error);
            }
